# Generated by Django 6.1 on 2026-09-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollmen_date',
            new_name='enrollment_date',
        ),
    ]
