# Generated by Django 6.1 on 2026-09-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_enrollmen_date_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
